spring:
  application:
    name: Bookstore
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:bookstoreDB
    driverClassName: org.h2.Driver
    username: sa
    password: sa123
  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:8080/h2-console
